# Generated by Django 3.2.9 on 2022-02-19 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bird_app', '0005_auto_20220219_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('body', models.TextField()),
                ('datePosted', models.DateTimeField(auto_now_add=True)),
                ('authorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bird_app.post')),
            ],
            options={
                'ordering': ['-datePosted', '-likes'],
            },
        ),
    ]
