# Generated by Django 3.2.9 on 2022-02-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_app', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='documents_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
